version: '3.1'

services:
  php-apache:
    container_name: digitepp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
    volumes:
      - ./:/var/www/html/
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf